### ISSUE TITLE
Elephant-Bird does not work with protoc 2.4

### ISSUE THREAD

**Issue by stevenbedrick** [twitter/elephant-bird#49]
Hello-

I'm running into trouble building elephant-bird. Ant is failing on the `compile-generated-protobuf` task, with errors that look like the protocol buffer jar file isn't ending up on the classpath:

```
Buildfile: /Users/steven/Desktop/Hacking/protobuf/elephant_bird/elephant-bird/build.xml

release:
     [echo] Building in release mode...

init:

compile-protobuf:
    [apply] Applied thrift to 1 file and 0 directories.
    [apply] Applied protoc to 4 files and 0 directories.
    [javac] Compiling 9 source files to /Users/steven/Desktop/Hacking/protobuf/elephant_bird/elephant-bird/build/classes
    [javac] /Users/steven/Desktop/Hacking/protobuf/elephant_bird/elephant-bird/build/gen-java/com/twitter/data/proto/BlockStorage.java:12: cannot find symbol
    [javac] symbol  : class MessageOrBuilder
    [javac] location: package com.google.protobuf
    [javac]       extends com.google.protobuf.MessageOrBuilder {
    [javac]                                  ^
    [javac]
... snip ...
/Users/steven/Desktop/Hacking/protobuf/elephant_bird/elephant-bird/build/gen-java/com/twitter/data/proto/tutorial/AddressBookProtos.java:1275: cannot find symbol
 [javac] symbol  : method onChanged()
 [javac] location: class com.twitter.data.proto.tutorial.AddressBookProtos.Person.Builder
 [javac]           onChanged();
 [javac]           ^
 [javac] Note: Some input files use unchecked or unsafe operations.
 [javac] Note: Recompile with -Xlint:unchecked for details.
 [javac] 100 errors
```

Any ideas what might be going on here? It's running `protoc` just fine, and from what I can tell from `build.xml`, javac's classpath _ought_ to include `protobuf-java-2.3.0.jar` from elephant-bird's  `lib` directory- but it sure looks like it isn't actually getting set up correctly.
